version: '3.5'

services:

  coocvectorizer:
    image: coocvectorizer:1.0
    build:
      context: .
    command:
      - /bin/sh
      - -c
      - |
        jupyter notebook --NotebookApp.token='password' --ip=0.0.0.0 --allow-root
    volumes:
      - .:/vectorizer
    ports:
      - "8889:8888"